In [1]:
import torch  ##미분 계산

In [2]:
x = torch.ones(2,2, requires_grad=True)# requires_grad는 기본적으로 false
print(x) # x에 관한 연산자를 모두 추적, 미분할 때 사용 # 크게보면 변수선언(+데이터입력)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [5]:
y = x+1 # 모델 내 연산 예측값 산출
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [6]:
z = 2*y**2 #손실함수 계산 #최적화란 손실함수 기준으로 각 변수마다 미분을 하는 것
res = z.mean()

In [7]:
print(res) #손실 산출

tensor(8., grad_fn=<MeanBackward0>)


In [8]:
#d(res)/dx_i = x_i + 1
# res = (z_1 + .. +z_4)/4
# z_i = 2 y_i **2
# z_i = 2(x_i+1)**2

res.backward() #backward는 연쇄법칙
print(x.grad) #x에 대한 미분값을 보고 싶으면 .grad 

tensor([[2., 2.],
        [2., 2.]])


In [9]:
import torch.nn as nn
import torch.nn.functional as F